# 설정
server:
  port: 8080

spring:
  # ?? ANSI ??
  output:
    ansi:
      enabled: always

  # Thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:/templates/views/

  # datasource 설정
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: dbmanaga
    password: 1234

  # JPA 설정
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect

  # security 설정
  security:
    user:
      name: user
      password: 1111

app:

  # 페이징 관련 세팅값
  pagination:
    write_pages: 10  # 기본 write_pages 값. 한 [페이징] 당 몇개의 페이지가 표시되나
    page_rows: 10    # 기본 page_rows 값.  한 '페이지'에 몇개의 글을 리스트 할것인가?

  #파일 업로드 경로
  upload:
    path: upload
